apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appdb
  template:
    metadata:
      labels:
        app: appdb
    spec:
      containers:
      - name: myapp
        image: vprofile/vprofiledb:V1

        volumeMounts:
          - name: vpro-db-data
            mountPath: /var/lib/mysql
        ports:
          - containerPort: 3306
            name: appdb-port
        env: 
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                app: app-secret
                key: db-pass

      nodeSelector: 
        zone: us-east-1a

      volumes:
        - name: vpro-db-data
          awsElasticBlockStore:
            volumeID: vol-038c4332b6658bdca
            fsType: ext4

      initContainers:
        - name: busybox
          image: busybox:latest
          args: ["rm","-rf","/var/lib/mysql/lost+found"]
          volumeMounts:
          - name: vpro-db-data
            mountPath: /var/lib/mysql



