apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
spec:
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
      - name: vproapp-container
        image: vprofile/vprofileapp:V1
        ports:
        - containerPort: 8080
          name: vproapp-port
          
      initContainers:
      - name: init-mydb
        image: busybox:latest
        command: ['sh', '-c', 'until nslookup vprodb.default.svc.cluster.local; do echo waiting for mysql; sleep 2; done;']

      - name: init-memecache
        image: busybox:latest
        command: ['sh', '-c', 'until nslookup vprocache01.default.svc.cluster.local; do echo waiting for memecache; sleep 2; done;']

